extends:
  - eslint:recommended
  - plugin:react/recommended

env:
  es6: true
  node: true
  browser: true

parser: "@babel/eslint-parser"

parserOptions:
  ecmaVersion: 2018
  sourceType: module

  ecmaFeatures:
    jsx: true

  requireConfigFile: false

  babelOptions:
    presets:
      - "@babel/preset-react"

settings:
  react:
    version: detect

rules:
  no-console: off
  react/prop-types: off
